In [45]:
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px

import sys; sys.path.append("..") #to direct program to the root files
from utils.get_data import get_processed_files

from datetime import datetime

In [ ]:
"""
Only run if there changes to ../utils/get_data folder
import importlib
import utils.get_data
importlib.reload(utils.get_data) #update with any changes made
"""

'\nOnly run if there changes to utils.get_data folder\nimport importlib\nimport utils.get_data\nimportlib.reload(utils.get_data) #update with any changes made\n'

In [47]:
# below are estimated date
TERRA_LUNA_CRASH_START_DATE = datetime.strptime("7 May 2022", "%d %B %Y")
GFC_CRASH_START_DATE = datetime.strptime("15 September 2008", "%d %B %Y")

In [3]:
erc_20_dfs = get_processed_files("..\\datasets\\processed\\erc_20")
erc_20_dfs

{'dai_price_data':      Unnamed: 0   timestamp    open  high     low   close        date
 0             0  1648857600  0.9999   1.0  0.9989  1.0000  2022-04-02
 1             1  1648944000  1.0000   1.0  0.9989  0.9990  2022-04-03
 2             2  1649030400  0.9990   1.0  0.9989  0.9995  2022-04-04
 3             3  1649116800  0.9994   1.0  0.9987  0.9999  2022-04-05
 4             4  1649203200  0.9999   1.0  0.9988  0.9991  2022-04-06
 ..          ...         ...     ...   ...     ...     ...         ...
 210         210  1667001600  0.9997   1.0  0.9987  1.0000  2022-10-29
 211         211  1667088000  1.0000   1.0  0.9991  1.0000  2022-10-30
 212         212  1667174400  1.0000   1.0  0.9989  1.0000  2022-10-31
 213         213  1667260800  1.0000   1.0  0.9983  0.9999  2022-11-01
 214         214  1667347200  0.9999   1.0  0.9990  0.9999  2022-11-02

 [215 rows x 7 columns],
 'event_data':     Unnamed: 0                                              event   timestamp  \
 0            0  BlackRock and Fidelity Back USDC in $400 Milli...  1649721600
 1            1  Terra UST takes over BUSD to become third larg...  1650412800
 2            2  LARGE amounts of UST selling on ANCHOR (approx...  1651881600
 3            3  UST depegs LFG deploys assets to defend peg (7...  1651968000
 4            4    UST Depegs again to 35 cents LUNA keeps falling  1652054400
 5            5                       LUNA Collapses by almost 99%  1652313600
 6            6  UST Downfall Brings Record Volumes to Curve: I...  1652313600
 7            7  Terra Halts Its Blockchain and Binance Suspend...  1652400000
 8            8     LUNA essentially worthless (1/100th of a cent)  1652486400
 9            9  Luna Foundation Guard 80000 Bitcoin Lighter Af...  1652659200
 10          10            Tether Token (USDT) Launches on Polygon  1653609600
 11          11            Tether Tokens (USDT) to Launch on Tezos  1654732800
 12          12  Binance CEO mentions selling 500million in FTX...  1654905600
 13          13  TRON DAO RESERVE DEPLOYS Funds (700million dep...  1655078400
 14          14  US$500 million in USDC added to TRON DAO USDD ...  1655078400
 15          15  Circle freezes blacklisted Tornado Cash smart ...  1659916800
 16          16  FTX shows sign of trouble and Binance CEO and ...  1660176000
 17          17  MakerDAO should seriously consider depegging D...  1660176000
 18          18         USDC whales leave and trading volume soars  1661126400
 19          19  Centre Consortium Announces Release of USD Coi...  1661904000
 20          20  MakerDAO Christensen Pushes Endgame Plan to Sa...  1661904000
 21          21  Binance Announces LUNC and USTC Deposit And Wi...  1662076800
 22          22  Luna price has picked momentum as the communit...  1662336000
 23          23  FTX To Suspend LUNC and USTC Deposits And With...  1662422400
 24          24  Binance - LUNC and USTC Deposits and Withdrawa...  1662508800
 25          25  Huobi And BTCEX Joins Binance To Support 1.2% ...  1662681600
 26          26                 Binance Backs out of Deal with FTX  1662854400
 27          27        Binance Announces Zero-Fee Trading For Luna  1662940800
 28          28             Tether (USDT) Launches on Near Network  1662940800
 29          29  FTX Suspends LUNA and UST Deposits and Withdra...  1663027200
 30          30  USDC coming to five additional blockchain ecos...  1664323200
 31          31  MakerDAO goes ahead with $500M investment in t...  1665100800
 32          32  USTC jumps over 35% in 24 hours as re-peg prop...  1665273600
 33          33         Binance Adds UST to Borrowable Assets List  1665619200
 34          34        Tether change reserves to US treasury bills  1665619200
 35          35                 UST Trading Vol Skyrockets By 240%  1666224000
 36          36  Tether announces Available in Over 24000 ATMs ...  1666224000
 37          37  UST climbs 15% in 24 hours reclaiming $400 mil...  1666828800

         type stablecoin        date
 0   positive       usdc  2022-04-12
 1   positive       ustc  2022-04-20
 2   negative       ustc  2022-05-07
 3   negative       ustc  2022-05-08
 4   negative       ustc  2022-05-09
 5   negative  lunaterra  2022-05-12
 6   negative       ustc  2022-05-12
 7   negative  lunaterra  2022-05-13
 8   negative  lunaterra  2022-05-14
 9   negative  lunaterra  2022-05-16
 10  positive       usdt  2022-05-27
 11  positive       usdt  2022-06-09
 12  negative    unknown  2022-06-11
 13  positive        dai  2022-06-13
 14  positive       usdc  2022-06-13
 15  negative       usdc  2022-08-08
 16  positive    unknown  2022-08-11
 17  negative        dai  2022-08-11
 18  negative       usdc  2022-08-22
 19  positive       usdc  2022-08-31
 20  positive        dai  2022-08-31
 21  negative  lunaterra  2022-09-02
 22  positive  lunaterra  2022-09-05
 23  negative  lunaterra  2022-09-06
 24  negative  lunaterra  2022-09-07
 25  positive  lunaterra  2022-09-09
 26  negative    unknown  2022-09-11
 27  positive    unknown  2022-09-12
 28  positive       usdt  2022-09-12
 29  negative  lunaterra  2022-09-13
 30  positive       usdc  2022-09-28
 31  positive        dai  2022-10-07
 32  positive       ustc  2022-10-09
 33  positive       ustc  2022-10-13
 34  positive       usdt  2022-10-13
 35  positive       ustc  2022-10-20
 36  positive       usdt  2022-10-20
 37  positive       ustc  2022-10-27  ,
 'pax_price_data':      Unnamed: 0   timestamp    open  high     low   close        date
 0             0  1648857600  1.0000  1.00  0.9962  1.0000  2022-04-02
 1             1  1648944000  1.0000  1.00  0.9982  1.0000  2022-04-03
 2             2  1649030400  1.0000  1.00  0.9975  1.0000  2022-04-04
 3             3  1649116800  1.0000  1.00  0.9986  1.0000  2022-04-05
 4             4  1649203200  1.0000  1.00  0.9973  0.9998  2022-04-06
 ..          ...         ...     ...   ...     ...     ...         ...
 210         210  1667001600  0.9953  1.00  0.9904  0.9994  2022-10-29
 211         211  1667088000  0.9994  1.00  0.9915  0.9971  2022-10-30
 212         212  1667174400  0.9970  1.00  0.9939  1.0000  2022-10-31
 213         213  1667260800  1.0000  1.00  0.9952  0.9973  2022-11-01
 214         214  1667347200  0.9990  1.01  0.9942  0.9983  2022-11-02

 [215 rows x 7 columns],
 'token_transfers':          block_number  transaction_index  \
 0            14669683                  7
 1            14669683                 45
 2            14669683                 46
 3            14669683                 47
 4            14669683                 48
 ...               ...                ...
 1565767      14734965                 69
 1565768      14734965                 70
 1565769      14734965                 71
 1565770      14734965                 72
 1565771      14734965                 97

                                        from_address  \
 0        0xd30b438df65f4f788563b2b3611bd6059bff4ad9
 1        0x4941834ed1428089ee76252f6f9d767e800499b0
 2        0x2c1f9a20711e14f8484a41123e20d1b06858ebea
 3        0x7784c4f53aa5f03bd6d3ca670c9d9c887cc38cb0
 4        0x66589b8278470d58d4112f3d065de0f75734312e
 ...                                             ...
 1565767  0xe9100f5aae85b41a7800cf0d0612308e110e204f
 1565768  0x26bdd2b467e900df7ff16c54ae39a4241d20d415
 1565769  0x5d7500d490207798dbc324ad85f027b825239e46
 1565770  0xcc87218307ea49110d3f75eda3a31fbb1b39312d
 1565771  0xbc430f8de65a5f70b05fe44c4d3e884f02c1da7a

                                          to_address  time_stamp  \
 0        0xda816e2122a8a39b0926bfa84edd3d42477e9efd  1651105815
 1        0x28c6c06298d514db089934071355e5743bf21d60  1651105815
 2        0x28c6c06298d514db089934071355e5743bf21d60  1651105815
 3        0x3cd751e6b0078be393132286c442345e5dc49699  1651105815
 4        0x28c6c06298d514db089934071355e5743bf21d60  1651105815
 ...                                             ...         ...
 1565767  0x0d0707963952f2fba59dd06f2b425ace40b492fe  1651998104
 1565768  0x0d0707963952f2fba59dd06f2b425ace40b492fe  1651998104
 1565769  0x0d0707963952f2fba59dd06f2b425ace40b492fe  1651998104
 1565770  0x0d0707963952f2fba59dd06f2b425ace40b492fe  1651998104
 1565771  0xd8a65f861001d93f30c89199d70b7607565200ee  1651998104

                                    contract_address         value  \
 0        0xdac17f958d2ee523a2206206994597c13d831ec7     18.670000
 1        0xdac17f958d2ee523a2206206994597c13d831ec7  10000.000000
 2        0xdac17f958d2ee523a2206206994597c13d831ec7   9942.313005
 3        0xdac17f958d2ee523a2206206994597c13d831ec7    234.364097
 4        0xdac17f958d2ee523a2206206994597c13d831ec7   9800.000000
 ...                                             ...           ...
 1565767  0xdac17f958d2ee523a2206206994597c13d831ec7   6432.300000
 1565768  0xdac17f958d2ee523a2206206994597c13d831ec7   6432.623398
 1565769  0xdac17f958d2ee523a2206206994597c13d831ec7   6429.490000
 1565770  0xdac17f958d2ee523a2206206994597c13d831ec7   6428.880000
 1565771  0xdac17f958d2ee523a2206206994597c13d831ec7   1500.000000

                         date
 0        2022-04-28 00:30:15
 1        2022-04-28 00:30:15
 2        2022-04-28 00:30:15
 3        2022-04-28 00:30:15
 4        2022-04-28 00:30:15
 ...                      ...
 1565767  2022-05-08 08:21:44
 1565768  2022-05-08 08:21:44
 1565769  2022-05-08 08:21:44
 1565770  2022-05-08 08:21:44
 1565771  2022-05-08 08:21:44

 [1565772 rows x 8 columns],
 'token_transfers_V2.0.0':           Unnamed: 0  block_number  transaction_index  \
 0                  0      14669683                  7
 1                  1      14669683                 45
 2                  2      14669683                 46
 3                  3      14669683                 47
 4                  4      14669683                 48
 ...              ...           ...                ...
 28674506    28674506      15693289                338
 28674507    28674507      15693289                342
 28674508    28674508      15693289                 20
 28674509    28674509      15693289                186
 28674510    28674510      15693289                231

                                         from_address  \
 0         0xd30b438df65f4f788563b2b3611bd6059bff4ad9
 1         0x4941834ed1428089ee76252f6f9d767e800499b0
 2         0x2c1f9a20711e14f8484a41123e20d1b06858ebea
 3         0x7784c4f53aa5f03bd6d3ca670c9d9c887cc38cb0
 4         0x66589b8278470d58d4112f3d065de0f75734312e
 ...                                              ...
 28674506  0x55fe002aeff02f77364de339a1292923a15844b8
 28674507  0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640
 28674508  0xbeefbabeea323f07c59926295205d3b7a17e8638
 28674509  0x53395e9e56f1b7fb3cd1fbd4c1195ef2dee71736
 28674510  0x56178a0d5f301baf6cf3e1cd53d9863437345bf9

                                           to_address  time_stamp  \
 0         0xda816e2122a8a39b0926bfa84edd3d42477e9efd  1651105815
 1         0x28c6c06298d514db089934071355e5743bf21d60  1651105815
 2         0x28c6c06298d514db089934071355e5743bf21d60  1651105815
 3         0x3cd751e6b0078be393132286c442345e5dc49699  1651105815
 4         0x28c6c06298d514db089934071355e5743bf21d60  1651105815
 ...                                              ...         ...
 28674506  0x0000000000000000000000000000000000000000  1665110327
 28674507  0x735a26a57a0a0069dfabd41595a970faf5e1ee8b  1665110327
 28674508  0x60594a405d53811d3bc4766596efd80fd545a270  1665110327
 28674509  0x48da0965ab2d2cbf1c17c09cfb5cbe67ad5b1406  1665110327
 28674510  0x60594a405d53811d3bc4766596efd80fd545a270  1665110327

                                     contract_address         value  \
 0         0xdac17f958d2ee523a2206206994597c13d831ec7     18.670000
 1         0xdac17f958d2ee523a2206206994597c13d831ec7  10000.000000
 2         0xdac17f958d2ee523a2206206994597c13d831ec7   9942.313005
 3         0xdac17f958d2ee523a2206206994597c13d831ec7    234.364097
 4         0xdac17f958d2ee523a2206206994597c13d831ec7   9800.000000
 ...                                              ...           ...
 28674506  0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48    853.630000
 28674507  0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48   3133.274260
 28674508  0x6b175474e89094c44da98b954eedeac495271d0f   5020.200000
 28674509  0x6b175474e89094c44da98b954eedeac495271d0f   3921.972387
 28674510  0x6b175474e89094c44da98b954eedeac495271d0f   5598.273150

                          date
 0         2022-04-28 00:30:15
 1         2022-04-28 00:30:15
 2         2022-04-28 00:30:15
 3         2022-04-28 00:30:15
 4         2022-04-28 00:30:15
 ...                       ...
 28674506  2022-10-07 02:38:47
 28674507  2022-10-07 02:38:47
 28674508  2022-10-07 02:38:47
 28674509  2022-10-07 02:38:47
 28674510  2022-10-07 02:38:47

 [28674511 rows x 9 columns],
 'token_transfers_V3.0.0':           Unnamed: 0  block_number  transaction_index  \
 0                  0      14500001                 44
 1                  1      14500001                 62
 2                  2      14500001                 64
 3                  3      14500001                 68
 4                  4      14500003                  0
 ...              ...           ...                ...
 36723650    36723650      15872937                 21
 36723651    36723651      15872937                 47
 36723652    36723652      15872937                 62
 36723653    36723653      15872937                 83
 36723654    36723654      15872937                 47

                                         from_address  \
 0         0x27cbb0e6885ccb1db2dab7c2314131c94795fbef
 1         0x7938b1b2f2d2ec6cde2db46fcb11d824f32eae54
 2         0x4593e0fb8dcc65cd24c7f99ee64da2627e90f998
 3         0x3cd751e6b0078be393132286c442345e5dc49699
 4         0xffec0067f5a79cff07527f63d83dd5462ccf8ba4
 ...                                              ...
 36723650  0x66e33d2605c5fb25ebb7cd7528e7997b0afa55e8
 36723651  0xaf0b0000f0210d0f421f0009c72406703b50506b
 36723652  0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640
 36723653  0x353bb62ed786cdf7624bd4049859182f3c1e9e5d
 36723654  0xb7e99263e381fdeafe70aecd33bab743fd77597e

                                           to_address  time_stamp  \
 0         0x8426a27add8dca73548f012d92c7f8f4bbd42a3e  1648811421
 1         0xffabc91efaf240a48fe2b31d3599925d3504c3df  1648811421
 2         0x97138e4cb36db0185236c3d74cb39fb51cb3228b  1648811421
 3         0xf4fc2e12974cc3b4d8192722430c571968025d4f  1648811421
 4         0x5b0e981798f5880c25b54c5de4005f5ec1f3f46a  1648811424
 ...                                              ...         ...
 36723650  0x0eae044f00b0af300500f090ea00027097d03000  1667278439
 36723651  0xb7e99263e381fdeafe70aecd33bab743fd77597e  1667278439
 36723652  0x02736d5c8dcea65539993d143a3de90cebca9c3c  1667278439
 36723653  0x02f7ab8d72daf2063368e89f23fe0db9b3cb3ffd  1667278439
 36723654  0xaf0b0000f0210d0f421f0009c72406703b50506b  1667278439

                                     contract_address         value  \
 0         0xdac17f958d2ee523a2206206994597c13d831ec7    800.000000
 1         0xdac17f958d2ee523a2206206994597c13d831ec7    579.000000
 2         0xdac17f958d2ee523a2206206994597c13d831ec7  15898.000000
 3         0xdac17f958d2ee523a2206206994597c13d831ec7    200.929675
 4         0xdac17f958d2ee523a2206206994597c13d831ec7    651.675449
 ...                                              ...           ...
 36723650  0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48     10.283114
 36723651  0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48     79.504357
 36723652  0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48    254.098146
 36723653  0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48  15178.209720
 36723654  0x6b175474e89094c44da98b954eedeac495271d0f     14.500000

                          date
 0         2022-04-01 11:10:21
 1         2022-04-01 11:10:21
 2         2022-04-01 11:10:21
 3         2022-04-01 11:10:21
 4         2022-04-01 11:10:24
 ...                       ...
 36723650  2022-11-01 04:53:59
 36723651  2022-11-01 04:53:59
 36723652  2022-11-01 04:53:59
 36723653  2022-11-01 04:53:59
 36723654  2022-11-01 04:53:59

 [36723655 rows x 9 columns],
 'usdc_price_data':      Unnamed: 0   timestamp    open  high     low   close        date
 0             0  1648857600  0.9995   1.0  0.9990  0.9999  2022-04-02
 1             1  1648944000  1.0000   1.0  0.9991  0.9993  2022-04-03
 2             2  1649030400  0.9993   1.0  0.9985  1.0000  2022-04-04
 3             3  1649116800  1.0000   1.0  0.9989  1.0000  2022-04-05
 4             4  1649203200  1.0000   1.0  0.9990  0.9997  2022-04-06
 ..          ...         ...     ...   ...     ...     ...         ...
 210         210  1667001600  0.9999   1.0  0.9997  0.9999  2022-10-29
 211         211  1667088000  0.9999   1.0  0.9997  1.0000  2022-10-30
 212         212  1667174400  1.0000   1.0  0.9998  1.0000  2022-10-31
 213         213  1667260800  1.0000   1.0  0.9995  0.9999  2022-11-01
 214         214  1667347200  1.0000   1.0  0.9997  1.0000  2022-11-02

 [215 rows x 7 columns],
 'usdt_price_data':      Unnamed: 0   timestamp    open    high     low   close        date
 0             0  1648857600  1.0000  1.0000  1.0000  1.0000  2022-04-02
 1             1  1648944000  1.0000  1.0000  1.0000  1.0000  2022-04-03
 2             2  1649030400  1.0000  1.0000  1.0000  1.0000  2022-04-04
 3             3  1649116800  1.0000  1.0000  1.0000  1.0000  2022-04-05
 4             4  1649203200  1.0000  1.0000  1.0000  1.0000  2022-04-06
 ..          ...         ...     ...     ...     ...     ...         ...
 210         210  1667001600  1.0000  1.0000  1.0000  1.0000  2022-10-29
 211         211  1667088000  1.0000  1.0000  1.0000  1.0000  2022-10-30
 212         212  1667174400  1.0000  1.0000  1.0000  1.0000  2022-10-31
 213         213  1667260800  1.0000  1.0000  0.9999  0.9999  2022-11-01
 214         214  1667347200  0.9999  0.9999  0.9998  0.9999  2022-11-02

 [215 rows x 7 columns],
 'ustc_price_data':      Unnamed: 0   timestamp     open     high      low    close        date
 0             0  1648857600  1.00000  1.00000  0.99890  1.00000  2022-04-02
 1             1  1648944000  1.00000  1.00000  0.99860  1.00000  2022-04-03
 2             2  1649030400  1.00000  1.00000  0.99900  0.99990  2022-04-04
 3             3  1649116800  0.99990  1.00000  0.99630  1.00000  2022-04-05
 4             4  1649203200  1.00000  1.00000  0.99760  0.99840  2022-04-06
 ..          ...         ...      ...      ...      ...      ...         ...
 210         210  1667001600  0.04155  0.04650  0.04108  0.04121  2022-10-29
 211         211  1667088000  0.04124  0.04231  0.03819  0.03860  2022-10-30
 212         212  1667174400  0.03860  0.04040  0.03787  0.03949  2022-10-31
 213         213  1667260800  0.03949  0.03955  0.03756  0.03776  2022-11-01
 214         214  1667347200  0.03776  0.03848  0.03715  0.03726  2022-11-02

 [215 rows x 7 columns],
 'wluna_price_data':      Unnamed: 0   timestamp        open        high         low       close  \
 0             0  1648857600  103.230000  107.280000  100.030000  105.870000
 1             1  1648944000  105.900000  116.740000  105.720000  115.490000
 2             2  1649030400  115.460000  116.990000  112.020000  113.460000
 3             3  1649116800  113.400000  116.410000  110.360000  115.960000
 4             4  1649203200  115.990000  118.190000  115.520000  116.100000
 ..          ...         ...         ...         ...         ...         ...
 210         210  1667001600    0.000239    0.000252    0.000235    0.000241
 211         211  1667088000    0.000241    0.000249    0.000229    0.000236
 212         212  1667174400    0.000236    0.000268    0.000230    0.000244
 213         213  1667260800    0.000244    0.000255    0.000233    0.000236
 214         214  1667347200    0.000236    0.000242    0.000210    0.000218

            date
 0    2022-04-02
 1    2022-04-03

In [4]:
gfc_dfs = get_processed_files("..\\datasets\\processed\\gfc_data")
gfc_dfs

{'AIG':            Price       Close        High         Low        Open    Volume  \
 0     2005-01-04  792.226868  799.999660  790.552699  793.422682    379110
 1     2005-01-05  805.380432  812.674866  796.651008  797.607644    558800
 2     2005-01-06  806.695984  812.435949  799.999456  801.195269    408765
 3     2005-01-07  808.130920  811.718362  804.304302  807.772191    311070
 4     2005-01-10  809.565979  811.838055  804.782724  807.413529    253345
 ...          ...         ...         ...         ...         ...       ...
 2006  2012-12-21   26.324486   26.665474   26.021382   26.460879  31856600
 2007  2012-12-24   26.673058   26.673058   26.172938   26.241136   6816400
 2008  2012-12-26   26.786713   26.847335   26.491188   26.756405  11728100
 2009  2012-12-27   26.498762   26.900372   26.066841   26.900372  16674800
 2010  2012-12-28   26.203245   26.513925   26.142623   26.218398  11919300

      ticker        date
 0       AIG  2005-01-04
 1       AIG  2005-01-05
 2       AIG  2005-01-06
 3       AIG  2005-01-07
 4       AIG  2005-01-10
 ...     ...         ...
 2006    AIG  2012-12-21
 2007    AIG  2012-12-24
 2008    AIG  2012-12-26
 2009    AIG  2012-12-27
 2010    AIG  2012-12-28

 [2011 rows x 8 columns],
 'C':            Price       Close        High         Low        Open    Volume  \
 0     2005-01-04  296.758362  302.400867  295.766270  299.362582   1584770
 1     2005-01-05  300.478668  302.462833  297.750430  297.936439   1893350
 2     2005-01-06  303.392761  305.314935  302.214661  302.586698   1804990
 3     2005-01-07  301.656769  304.509026  301.346741  304.447016   1280370
 4     2005-01-10  299.734558  302.214778  297.750394  300.788659   1699870
 ...          ...         ...         ...         ...         ...       ...
 2006  2012-12-21   29.363487   29.482458   28.627354   28.924782  47568200
 2007  2012-12-24   29.281693   29.408098   29.118107   29.251949   8674800
 2008  2012-12-26   29.408098   29.556812   29.132979   29.303999  20297700
 2009  2012-12-27   29.185034   29.653482   28.694279   29.504768  30332300
 2010  2012-12-28   29.006573   29.185030   28.828118   28.865296  24563800

      ticker        date
 0         C  2005-01-04
 1         C  2005-01-05
 2         C  2005-01-06
 3         C  2005-01-07
 4         C  2005-01-10
 ...     ...         ...
 2006      C  2012-12-21
 2007      C  2012-12-24
 2008      C  2012-12-26
 2009      C  2012-12-27
 2010      C  2012-12-28

 [2011 rows x 8 columns],
 'JPM':            Price      Close       High        Low       Open    Volume ticker  \
 0     2005-01-04  22.138395  22.513037  22.086522  22.466926  11360900    JPM
 1     2005-01-05  22.184513  22.432351  22.126875  22.247912   9770200    JPM
 2     2005-01-06  22.311308  22.466928  22.270962  22.345891   9115900    JPM
 3     2005-01-07  22.132629  22.403522  22.126864  22.299775   9971200    JPM
 4     2005-01-10  22.057705  22.196033  21.930903  22.057705   9284500    JPM
 ...          ...        ...        ...        ...        ...       ...    ...
 2006  2012-12-21  30.963045  31.103787  30.498600  30.836378  38973500    JPM
 2007  2012-12-24  30.906742  30.977114  30.758965  30.766003   8621200    JPM
 2008  2012-12-26  30.934900  31.089716  30.766012  30.927864  11498900    JPM
 2009  2012-12-27  30.702671  30.977116  30.188966  30.934892  19567000    JPM
 2010  2012-12-28  30.428242  30.744907  30.322685  30.329721  15401200    JPM

             date
 0     2005-01-04
 1     2005-01-05
 2     2005-01-06
 3     2005-01-07
 4     2005-01-10
 ...          ...
 2006  2012-12-21
 2007  2012-12-24
 2008  2012-12-26
 2009  2012-12-27
 2010  2012-12-28

 [2011 rows x 8 columns],
 'TEDRATE':      observation_date  TEDRATE  ticker        date
 0          2005-01-07     0.33    0.27  2005-01-07
 1          2005-01-10     0.29    0.27  2005-01-10
 2          2005-01-11     0.32    0.27  2005-01-11
 3          2005-01-12     0.34    0.27  2005-01-12
 4          2005-01-13     0.35    0.27  2005-01-13
 ...               ...      ...     ...         ...
 2077       2012-12-25      NaN    0.27  2012-12-25
 2078       2012-12-26      NaN    0.27  2012-12-26
 2079       2012-12-27     0.23    0.27  2012-12-27
 2080       2012-12-28     0.30    0.27  2012-12-28
 2081       2012-12-31     0.26    0.27  2012-12-31

 [2082 rows x 4 columns],
 'WGS3MO':     observation_date  WGS3MO  ticker        date
 0         2005-01-28    2.41    2.32  2005-01-28
 1         2005-02-04    2.50    2.32  2005-02-04
 2         2005-02-11    2.51    2.32  2005-02-11
 3         2005-02-18    2.59    2.32  2005-02-18
 4         2005-02-25    2.69    2.32  2005-02-25
 ..               ...     ...     ...         ...
 409       2012-11-30    0.09    2.32  2012-11-30
 410       2012-12-07    0.10    2.32  2012-12-07
 411       2012-12-14    0.07    2.32  2012-12-14
 412       2012-12-21    0.06    2.32  2012-12-21
 413       2012-12-28    0.06    2.32  2012-12-28

 [414 rows x 4 columns],
 '^DJI':            Price         Close          High           Low          Open  \
 0     2005-01-04  10630.780273  10769.559570  10605.150391  10727.809570
 1     2005-01-05  10597.830078  10684.429688  10597.750000  10629.530273
 2     2005-01-06  10622.879883  10667.580078  10589.330078  10593.190430
 3     2005-01-07  10603.959961  10653.250000  10571.740234  10624.799805
 4     2005-01-10  10621.030273  10663.740234  10582.379883  10603.440430
 ...          ...           ...           ...           ...           ...
 2006  2012-12-21  13190.839844  13309.950195  13122.530273  13309.950195
 2007  2012-12-24  13138.929688  13190.379883  13128.549805  13190.150391
 2008  2012-12-26  13114.589844  13174.879883  13076.870117  13138.849609
 2009  2012-12-27  13096.309570  13141.740234  12964.080078  13114.969727
 2010  2012-12-28  12938.110352  13095.459961  12926.860352  13095.080078

          Volume ticker        date
 0     293280000   ^DJI  2005-01-04
 1     263550000   ^DJI  2005-01-05
 2     232850000   ^DJI  2005-01-06
 3     283770000   ^DJI  2005-01-07
 4     279500000   ^DJI  2005-01-10
 ...         ...    ...         ...
 2006  413270000   ^DJI  2012-12-21
 2007   47710000   ^DJI  2012-12-24
 2008   79410000   ^DJI  2012-12-26
 2009  100160000   ^DJI  2012-12-27
 2010   85980000   ^DJI  2012-12-28

 [2011 rows x 8 columns],
 '^GSPC':            Price        Close         High          Low         Open  \
 0     2005-01-04  1188.050049  1205.839966  1185.390015  1202.079956
 1     2005-01-05  1183.739990  1192.729980  1183.719971  1188.050049
 2     2005-01-06  1187.890015  1191.630005  1183.270020  1183.739990
 3     2005-01-07  1186.189941  1192.199951  1182.160034  1187.890015
 4     2005-01-10  1190.250000  1194.780029  1184.800049  1186.189941
 ...          ...          ...          ...          ...          ...
 2006  2012-12-21  1430.150024  1443.670044  1422.579956  1443.670044
 2007  2012-12-24  1426.660034  1430.150024  1424.660034  1430.150024
 2008  2012-12-26  1419.829956  1429.420044  1416.430054  1426.660034
 2009  2012-12-27  1418.099976  1422.800049  1401.800049  1419.829956
 2010  2012-12-28  1402.430054  1418.099976  1401.579956  1418.099976

           Volume ticker        date
 0     1721000000  ^GSPC  2005-01-04
 1     1738900000  ^GSPC  2005-01-05
 2     1569100000  ^GSPC  2005-01-06
 3     1477900000  ^GSPC  2005-01-07
 4     1490400000  ^GSPC  2005-01-10
 ...          ...    ...         ...
 2006  5229160000  ^GSPC  2012-12-21
 2007  1248960000  ^GSPC  2012-12-24
 2008  2285030000  ^GSPC  2012-12-26
 2009  2830180000  ^GSPC  2012-12-27
 2010  2426680000  ^GSPC  2012-12-28

 [2011 rows x 8 columns],
 '^VIX':            Price      Close       High        Low       Open  Volume ticker  \
 0     2005-01-04  13.980000  14.450000  13.930000  14.010000       0   ^VIX
 1     2005-01-05  14.090000  14.090000  13.260000  13.980000       0   ^VIX
 2     2005-01-06  13.580000  14.090000  13.330000  14.090000       0   ^VIX
 3     2005-01-07  13.490000  13.510000  12.940000  13.470000       0   ^VIX
 4     2005-01-10  13.230000  13.930000  12.940000  13.920000       0   ^VIX
 ...          ...        ...        ...        ...        ...     ...    ...
 2006  2012-12-21  17.840000  19.930000  17.760000  19.850000       0   ^VIX
 2007  2012-12-24  17.840000  18.660000  17.840000  18.459999       0   ^VIX
 2008  2012-12-26  19.480000  19.629999  18.610001  18.709999       0   ^VIX
 2009  2012-12-27  19.469999  20.900000  19.110001  19.389999       0   ^VIX
 2010  2012-12-28  22.719999  23.230000  19.940001  20.320000       0   ^VIX

             date
 0     2005-01-04
 1     2005-01-05
 2     2005-01-06
 3     2005-01-07
 4     2005-01-10
 ...          ...
 2006  2012-12-21
 2007  2012-12-24
 2008  2012-12-26
 2009  2012-12-27
 2010  2012-12-28

 [2011 rows x 8 columns]}

In [ ]:
def create_candleLit_graph(df, name):
    """
    Show the trend of high, open, low, close prices

    Args:
        df -> pd.DataFrame
            should consist of the following columns ("open", "high", "low", "close", "date")
        name -> String, Name of the coin , or stocks , etc
    Output:
        candlestick chart
    """
    try :
        fig = go.Figure(data=[go.Candlestick(
            x=df.date,
            open=df['Open'],
            high=df['High'],
            low=df['Low'],
            close=df['Close'],
            increasing_line_color='green',
            decreasing_line_color='red'
        )])

        fig.add_shape(
            type="line", x0=TERRA_LUNA_CRASH_START_DATE, x1=TERRA_LUNA_CRASH_START_DATE, y0=df.Low.min(), y1=df.High.max() + 0.2,
            line=dict(color="red", width=1, dash="dash")
        )

        fig.update_layout(title=f'Price changes for {name}', xaxis_title='Date', yaxis_title="Prices")
        fig.show()
    except :
        print("unable to create candlestick chart")
        print("columns in df", df.columns.tolist())
        return

def create_line_graph(df, x, y, hue):
    """
    Analysing how input x column differ across y and for each hue
    using Line graph

    Args:
        df:
            pd.DataFrame (consisting of x,y,hue columns)
        x:
            string (name of column to be displayed as x-axis on line graph)
        y:
            string (name of column to be displayed as y-axis on line graph)
        hue:
            string (name of column to be displayed as hue on line graph)

    Output:
        Line graph figure
    """
    fig = px.line(df, x=x, y=y, color=hue)
    fig.add_shape(
        type="line", x0=TERRA_LUNA_CRASH_START_DATE, x1=TERRA_LUNA_CRASH_START_DATE, y0=df[y].min(), y1=df[y].max(),
        line=dict(color="red", width=1, dash="dash")
    )
    fig.update_layout(title=f'{y} Price changes across time', xaxis_title=x, yaxis_title=f"{y} prices")
    fig.show()

### Concat related files
- concat all price_data
- concat all gfc data

In [35]:
price_data = None
for name, df in erc_20_dfs.items():
    if name.endswith("price_data"):
        print("merging ", name)
        df["coins"] = name.split("_")[0] #because file name is processed_<coin_name>_price_data.csv
        df = df.rename(columns={'open': 'Open', 'low': 'Low', 'close': 'Close', 'high': 'High'})
        if (price_data is None):
            price_data = df
        else:
            price_data = pd.concat([price_data, df])

        print("analysing individual candle chart")
        create_candleLit_graph(df, name.split("_")[0])
    if "Unnamed: 0" in df.columns.tolist(): #drop unnamed column
        df.drop("Unnamed: 0", axis=1, inplace=True)

merging  dai_price_data
analysing individual candle chart

merging  pax_price_data
analysing individual candle chart

merging  usdc_price_data
analysing individual candle chart

merging  usdt_price_data
analysing individual candle chart

merging  ustc_price_data
analysing individual candle chart

merging  wluna_price_data
analysing individual candle chart

In [7]:
gfc_data = None
for name, df in gfc_dfs.items():
    print("merging ", name)
    if (gfc_data is None):
        gfc_data = df
    else:
        gfc_data = pd.concat([gfc_data, df])

    print("analysing individual candle chart")
    create_candleLit_graph(df, name)
    if "Unnamed: 0" in df.columns.tolist(): #drop unnamed column
        df.drop("Unnamed: 0", axis=1, inplace=True)

merging  AIG
analysing individual candle chart

merging  C
analysing individual candle chart

merging  JPM
analysing individual candle chart

merging  TEDRATE
analysing individual candle chart
unable to create candlestick chart
columns in df ['observation_date', 'TEDRATE', 'ticker', 'date']
merging  WGS3MO
analysing individual candle chart
unable to create candlestick chart
columns in df ['observation_date', 'WGS3MO', 'ticker', 'date']
merging  ^DJI
analysing individual candle chart

merging  ^GSPC
analysing individual candle chart

merging  ^VIX
analysing individual candle chart

In [ ]:
gfc_data

In [ ]:
price_data

# Analysing data

In [14]:
gfc_data

,Price,Close,High,Low,Open,Volume,ticker,date,observation_date,TEDRATE,WGS3MO
0,2005-01-04,792.226868,799.999660,790.552699,793.422682,379110.0,AIG,2005-01-04,NaN,NaN,NaN
1,2005-01-05,805.380432,812.674866,796.651008,797.607644,558800.0,AIG,2005-01-05,NaN,NaN,NaN
2,2005-01-06,806.695984,812.435949,799.999456,801.195269,408765.0,AIG,2005-01-06,NaN,NaN,NaN
3,2005-01-07,808.130920,811.718362,804.304302,807.772191,311070.0,AIG,2005-01-07,NaN,NaN,NaN
4,2005-01-10,809.565979,811.838055,804.782724,807.413529,253345.0,AIG,2005-01-10,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2006,2012-12-21,17.840000,19.930000,17.760000,19.850000,0.0,^VIX,2012-12-21,NaN,NaN,NaN
2007,2012-12-24,17.840000,18.660000,17.840000,18.459999,0.0,^VIX,2012-12-24,NaN,NaN,NaN
2008,2012-12-26,19.480000,19.629999,18.610001,18.709999,0.0,^VIX,2012-12-26,NaN,NaN,NaN
2009,2012-12-27,19.469999,20.900000,19.110001,19.389999,0.0,^VIX,2012-12-27,NaN,NaN,NaN
2010,2012-12-28,22.719999,23.230000,19.940001,20.320000,0.0,^VIX,2012-12-28,NaN,NaN,NaN

In [17]:
price_data

      timestamp      Open      High       Low     Close        date  coins
0    1648857600  0.999900  1.000000  0.998900  1.000000  2022-04-02    dai
1    1648944000  1.000000  1.000000  0.998900  0.999000  2022-04-03    dai
2    1649030400  0.999000  1.000000  0.998900  0.999500  2022-04-04    dai
3    1649116800  0.999400  1.000000  0.998700  0.999900  2022-04-05    dai
4    1649203200  0.999900  1.000000  0.998800  0.999100  2022-04-06    dai
..          ...       ...       ...       ...       ...         ...    ...
210  1667001600  0.000239  0.000252  0.000235  0.000241  2022-10-29  wluna
211  1667088000  0.000241  0.000249  0.000229  0.000236  2022-10-30  wluna
212  1667174400  0.000236  0.000268  0.000230  0.000244  2022-10-31  wluna
213  1667260800  0.000244  0.000255  0.000233  0.000236  2022-11-01  wluna
214  1667347200  0.000236  0.000242  0.000210  0.000218  2022-11-02  wluna

[1290 rows x 7 columns]

## Analysing coin prices for ERC20

In [58]:
create_line_graph(price_data[price_data['coins'] != "wluna"], 'date', 'Open', 'coins')
create_line_graph(price_data[price_data['coins'] != "wluna"], 'date', 'Close', 'coins')
create_line_graph(price_data[price_data['coins'] != "wluna"], 'date', 'High', 'coins')
create_line_graph(price_data[price_data['coins'] != "wluna"], 'date', 'Low', 'coins')

In [61]:
create_line_graph(price_data[~price_data['coins'].isin(["wluna", "ustc"])], 'date', 'Open', 'coins')
create_line_graph(price_data[~price_data['coins'].isin(["wluna", "ustc"])], 'date', 'Close', 'coins')
create_line_graph(price_data[~price_data['coins'].isin(["wluna", "ustc"])], 'date', 'High', 'coins')
create_line_graph(price_data[~price_data['coins'].isin(["wluna", "ustc"])], 'date', 'Low', 'coins')